- hosts: webserver
  become: true

  collections:
    - community.docker

  pre_tasks:
    - name: Instalar python3-pip
      apt:
        name: python3-pip
        state: present

    - name: Instalar la biblioteca Docker de Python
      pip:
        name: docker

  roles:
    - docker
    - jenkins
